/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/devices/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem a one-time partner-issued station pairing code
         * @description PROPOSED, not an existing Padel House route. See docs/partner-handoff.md for transactional, timing, and retry semantics.
         */
        post: operations["enrollDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/{station_id}/credentials/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate credentials using a station-scoped renewal secret
         * @description PROPOSED, not an existing Padel House route. See docs/partner-handoff.md for transactional, timing, and retry semantics.
         */
        post: operations["renewCredentials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/{station_id}/credentials/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke this station credential family only
         * @description PROPOSED, not an existing Padel House route. See docs/partner-handoff.md for transactional, timing, and retry semantics.
         */
        post: operations["revokeOwnCredentials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/{station_id}/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read station configuration without billing controls
         * @description PROPOSED, not an existing Padel House route. See docs/partner-handoff.md for transactional, timing, and retry semantics.
         */
        get: operations["getConfiguration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/{station_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read authorization and authoritative station/session state
         * @description PROPOSED, not an existing Padel House route. See docs/partner-handoff.md for transactional, timing, and retry semantics.
         */
        get: operations["getStationSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/{station_id}/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a station-owned session snapshot
         * @description PROPOSED, not an existing Padel House route. See docs/partner-handoff.md for transactional, timing, and retry semantics.
         */
        get: operations["getSessionSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/{station_id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report liveness and currently observed game processes
         * @description PROPOSED, not an existing Padel House route. See docs/partner-handoff.md for transactional, timing, and retry semantics.
         */
        post: operations["sendHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/{station_id}/launches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Obtain an expiring launch permit under cashier authorization
         * @description PROPOSED, not an existing Padel House route. See docs/partner-handoff.md for transactional, timing, and retry semantics.
         */
        post: operations["requestLaunch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/{station_id}/launches/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a launch attempt without ending billing or resetting grace
         * @description PROPOSED, not an existing Padel House route. See docs/partner-handoff.md for transactional, timing, and retry semantics.
         */
        post: operations["cancelLaunchAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/{station_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit durable observations without client-calculated charges
         * @description PROPOSED, not an existing Padel House route. See docs/partner-handoff.md for transactional, timing, and retry semantics.
         */
        post: operations["submitEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/{station_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll expiring station-scoped restriction commands
         * @description PROPOSED, not an existing Padel House route. See docs/partner-handoff.md for transactional, timing, and retry semantics.
         */
        get: operations["pollCommands"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/{station_id}/commands/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report verified restriction or honest enforcement failure
         * @description PROPOSED, not an existing Padel House route. See docs/partner-handoff.md for transactional, timing, and retry semantics.
         */
        post: operations["acknowledgeCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            station_id: string | null;
            session_id: string | null;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            server_time: string;
            /** @enum {string} */
            code: "INVALID_REQUEST" | "UNAUTHENTICATED" | "CREDENTIAL_REVOKED" | "FORBIDDEN_STATION" | "PAIRING_EXPIRED" | "AUTHORIZATION_REQUIRED" | "AUTHORIZATION_EXPIRED" | "STATION_UNAVAILABLE" | "SESSION_MISMATCH" | "REVISION_CONFLICT" | "IDEMPOTENCY_CONFLICT" | "ATTEMPT_EXPIRED" | "ATTEMPT_CANCELLED" | "GAME_NOT_ALLOWED" | "STALE_EVENT" | "SEQUENCE_CONFLICT" | "COMMAND_EXPIRED" | "UNSUPPORTED_COMMAND" | "RATE_LIMITED" | "TEMPORARILY_UNAVAILABLE";
            /** @description Safe diagnostic without secrets or customer credentials. */
            message: string;
            retryable: boolean;
            retry_after_seconds: number | null;
        };
        EnrollRequest: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            sent_at: string;
            /** @description One-use code entered through protected setup. */
            pairing_code: string;
            /** Format: uuid */
            installation_id: string;
            /** @description Installed application version. */
            agent_version: string;
            /** @description Requested label, backend assigns identity. */
            station_label: string;
        };
        Credentials: {
            /** Format: uuid */
            credential_id: string;
            /** @description Opaque secret. Never log or expose to the renderer. */
            access_token: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            expires_at: string;
            /** @description Opaque secret. Never log or expose to the renderer. */
            renewal_token: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            renewal_expires_at: string;
        };
        EnrollResponse: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            server_time: string;
            /** @description Backend-approved station label. */
            station_label: string;
            credentials: components["schemas"]["Credentials"];
        };
        RenewRequest: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            sent_at: string;
            /** Format: uuid */
            credential_id: string;
            /** @description Opaque secret. Never log or expose to the renderer. */
            renewal_token: string;
        };
        RenewResponse: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            server_time: string;
            credentials: components["schemas"]["Credentials"];
        };
        RevokeRequest: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            sent_at: string;
            /** Format: uuid */
            credential_id: string;
        };
        RevokeResponse: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            server_time: string;
            /** @constant */
            revoked: true;
        };
        Authorization: {
            /** Format: uuid */
            authorization_id: string;
            station_epoch: number;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            expires_at: string;
            opaque_ticket_reference: string | null;
        };
        Amount: {
            /** @description ISO 4217 currency. */
            currency: string;
            /** @description Backend-calculated decimal string; do not recalculate. */
            decimal_amount: string;
            /** @description Formatted by backend for display. */
            display_text: string;
            is_final: boolean;
        };
        Session: {
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            authorization_id: string;
            station_epoch: number;
            revision: number;
            /** @enum {string} */
            state: "pending" | "active" | "ended" | "cancelled";
            /** @description Immutable policy snapshot reference. Raw rate and delay settings are not device controls. */
            policy_version: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            accepted_first_play_at: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            grace_deadline_at: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            pending_expires_at: string;
            billable_start_at: string | null;
            ended_at: string | null;
            billable_seconds_at_server_time: number | null;
            display_amount: components["schemas"]["Amount"] | null;
        };
        Restriction: {
            /** @enum {string} */
            state: "unknown" | "unrestricted" | "pending" | "restricted" | "failed";
            command_id: string | null;
            verified_at: string | null;
            failure_code: string | null;
        };
        Snapshot: {
            revision: number;
            station_epoch: number;
            authorization: components["schemas"]["Authorization"] | null;
            session: components["schemas"]["Session"] | null;
            restriction: components["schemas"]["Restriction"];
            authorized_play_until: string | null;
            /** @description Backend decision; ended billing alone does not make a station available. */
            reassignable: boolean;
        };
        ProcessProfile: {
            executable_names: string[];
            /** @description Protected absolute local root; resolve canonical path and prohibit player-writable launch targets. */
            expected_install_root: string;
            launch_timeout_seconds: number;
            /** @enum {string} */
            handoff_strategy: "direct_process" | "steam_process";
        };
        SteamLaunch: {
            /** @constant */
            type: "steam";
            /** @description Digits only; construct supported Steam URI locally. */
            app_id: string;
        };
        ExecutableLaunch: {
            /** @constant */
            type: "executable";
            /** @description Admin-approved absolute Windows executable path. Never a command line or URL. */
            executable_path: string;
            arguments: string[];
            /** @description Validated absolute Windows directory. */
            working_directory: string;
        };
        GameProfile: {
            /** @description Stable ID resolved through the protected station catalog. */
            game_id: string;
            /** @description Display title. */
            title: string;
            artwork_asset: string | null;
            /** @description Category name. */
            category: string;
            controller: boolean;
            multiplayer: boolean;
            enabled: boolean;
            /** @description Locally verified per station; central claims do not prove installation. */
            installed: boolean;
            launch: components["schemas"]["SteamLaunch"] | components["schemas"]["ExecutableLaunch"];
            detection: components["schemas"]["ProcessProfile"];
        };
        StationConfig: {
            config_version: number;
            /** @description PC label. */
            station_label: string;
            planned_station_count: number;
            /** @constant */
            business_timezone: "Asia/Baghdad";
            heartbeat_interval_seconds: number;
            command_poll_interval_seconds: number;
            observation_freshness_seconds: number;
            pending_launch_offline_timeout_seconds: number;
            restriction_profile_id: string | null;
            catalog_revision: string | null;
        };
        ConfigResponse: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            server_time: string;
            config: components["schemas"]["StationConfig"];
        };
        SnapshotResponse: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            server_time: string;
            snapshot: components["schemas"]["Snapshot"];
        };
        RunningObservation: {
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            attempt_id: string;
            /** Format: uuid */
            game_run_id: string;
            /** @description Stable ID resolved through the protected station catalog. */
            game_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            process_started_at: string;
        };
        HeartbeatRequest: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            sent_at: string;
            /** Format: uuid */
            boot_id: string;
            sequence: number;
            monotonic_elapsed_ms: number;
            session_id: string | null;
            last_snapshot_revision: number;
            restriction: components["schemas"]["Restriction"];
            running_games: components["schemas"]["RunningObservation"][];
            outbox_depth: number;
        };
        LaunchRequest: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            sent_at: string;
            session_id: string | null;
            /** Format: uuid */
            authorization_id: string;
            station_epoch: number;
            /** @description Stable ID resolved through the protected station catalog. */
            game_id: string;
            /** Format: uuid */
            boot_id: string;
            expected_snapshot_revision: number;
        };
        LaunchAttempt: {
            /** Format: uuid */
            attempt_id: string;
            /** Format: uuid */
            session_id: string;
            /** @description Stable ID resolved through the protected station catalog. */
            game_id: string;
            station_epoch: number;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            issued_at: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            expires_at: string;
            /** @enum {string} */
            state: "permitted" | "running" | "failed" | "cancelled" | "expired";
        };
        LaunchResponse: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            server_time: string;
            snapshot: components["schemas"]["Snapshot"];
            attempt: components["schemas"]["LaunchAttempt"];
        };
        CancelLaunchRequest: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            sent_at: string;
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            attempt_id: string;
            /** @enum {string} */
            reason: "player_cancelled" | "launch_timeout" | "agent_recovery" | "communication_lost";
        };
        GameRunningEvent: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            event_id: string;
            /** Format: uuid */
            station_id: string;
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            boot_id: string;
            sequence: number;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            observed_at: string;
            monotonic_elapsed_ms: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "game_running";
            /** Format: uuid */
            attempt_id: string;
            /** Format: uuid */
            game_run_id: string;
            /** @description Stable ID resolved through the protected station catalog. */
            game_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            process_started_at: string;
            /** @description Protected local profile revision. */
            detection_profile_version: string;
        };
        LaunchFailedEvent: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            event_id: string;
            /** Format: uuid */
            station_id: string;
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            boot_id: string;
            sequence: number;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            observed_at: string;
            monotonic_elapsed_ms: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "launch_failed";
            /** Format: uuid */
            attempt_id: string;
            /** @description Stable ID resolved through the protected station catalog. */
            game_id: string;
            /** @enum {string} */
            reason: "timeout" | "not_installed" | "login_required" | "process_unreliable" | "start_failed" | "communication_lost";
            diagnostic: string | null;
        };
        GameExitedEvent: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            event_id: string;
            /** Format: uuid */
            station_id: string;
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            boot_id: string;
            sequence: number;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            observed_at: string;
            monotonic_elapsed_ms: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "game_exited";
            /** Format: uuid */
            attempt_id: string;
            /** Format: uuid */
            game_run_id: string;
            /** @description Stable ID resolved through the protected station catalog. */
            game_id: string;
            exit_code: number | null;
        };
        ObservedUseEvent: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            event_id: string;
            /** Format: uuid */
            station_id: string;
            /** Format: uuid */
            session_id: string;
            /** Format: uuid */
            boot_id: string;
            sequence: number;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            observed_at: string;
            monotonic_elapsed_ms: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "station_use_observed";
            /** Format: uuid */
            segment_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            segment_started_at: string;
            observed_station_use_seconds: number;
            /** @enum {string} */
            coverage: "continuous" | "recovered_unverified";
        };
        StationEvent: components["schemas"]["GameRunningEvent"] | components["schemas"]["LaunchFailedEvent"] | components["schemas"]["GameExitedEvent"] | components["schemas"]["ObservedUseEvent"];
        EventsRequest: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            sent_at: string;
            events: components["schemas"]["StationEvent"][];
        };
        EventResult: {
            /** Format: uuid */
            event_id: string;
            /** @enum {string} */
            outcome: "accepted" | "duplicate" | "rejected" | "retry";
            code: ("STALE_EVENT" | "SESSION_MISMATCH" | "ATTEMPT_EXPIRED" | "ATTEMPT_CANCELLED" | "SEQUENCE_CONFLICT" | "INVALID_REQUEST" | "TEMPORARILY_UNAVAILABLE") | null;
        };
        EventsResponse: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            server_time: string;
            results: components["schemas"]["EventResult"][];
            snapshot: components["schemas"]["Snapshot"];
        };
        RestrictCommand: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            command_id: string;
            /** Format: uuid */
            station_id: string;
            /** Format: uuid */
            session_id: string;
            station_epoch: number;
            session_revision: number;
            /** @constant */
            type: "restrict_station";
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            issued_at: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            expires_at: string;
            /** @description Must match locally approved and implemented profile. */
            restriction_profile_id: string;
            /** @enum {string} */
            reason: "cashier_session_ended" | "authorization_expired";
        };
        CommandsResponse: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            server_time: string;
            commands: components["schemas"]["RestrictCommand"][];
            next_cursor: string | null;
            snapshot: components["schemas"]["Snapshot"];
        };
        CommandResultRequest: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            sent_at: string;
            /** Format: uuid */
            session_id: string;
            station_epoch: number;
            /** Format: uuid */
            command_id: string;
            /** Format: uuid */
            boot_id: string;
            /** Format: uuid */
            result_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            attempted_at: string;
            /** @enum {string} */
            outcome: "verified" | "failed" | "rejected_stale" | "expired" | "unsupported";
            /** @enum {string} */
            restriction_state: "restricted" | "failed" | "unknown";
            verified_at: string | null;
            evidence: string | null;
            failure_code: string | null;
        };
        CommandResultResponse: {
            /** @constant */
            api_version: "1";
            /** Format: uuid */
            request_id: string;
            /** Format: uuid */
            station_id: string;
            /**
             * Format: date-time
             * @description UTC RFC3339 timestamp ending in Z. Server validates device observations; device wall time is not financial authority.
             */
            server_time: string;
            /** Format: uuid */
            command_id: string;
            /** Format: uuid */
            result_id: string;
            /** @constant */
            recorded: true;
            snapshot: components["schemas"]["Snapshot"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    enrollDevice: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable UUID for one logical mutation; same key + different canonical payload returns 409. Reuse identical body on retry. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollRequest"];
            };
        };
        responses: {
            /** @description Accepted response. A launch permit is not proof that a game is running or billing has started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollResponse"];
                };
            };
            /** @description Invalid message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Credential, renewal token, or pairing code invalid/expired/revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Station scope or authorization rejected. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session, revision, sequence, or idempotency conflict; reconcile before a new action. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Expired authorization, attempt, or command. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Back off using Retry-After. */
            429: {
                headers: {
                    /** @description Seconds before retry. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Transient failure; retry with stable identifiers and backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    renewCredentials: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable UUID for one logical mutation; same key + different canonical payload returns 409. Reuse identical body on retry. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Must equal the authenticated station ID and any station ID in the body. */
                station_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenewRequest"];
            };
        };
        responses: {
            /** @description Accepted response. A launch permit is not proof that a game is running or billing has started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenewResponse"];
                };
            };
            /** @description Invalid message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Credential, renewal token, or pairing code invalid/expired/revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Station scope or authorization rejected. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session, revision, sequence, or idempotency conflict; reconcile before a new action. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Expired authorization, attempt, or command. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Back off using Retry-After. */
            429: {
                headers: {
                    /** @description Seconds before retry. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Transient failure; retry with stable identifiers and backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    revokeOwnCredentials: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable UUID for one logical mutation; same key + different canonical payload returns 409. Reuse identical body on retry. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Must equal the authenticated station ID and any station ID in the body. */
                station_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeRequest"];
            };
        };
        responses: {
            /** @description Accepted response. A launch permit is not proof that a game is running or billing has started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeResponse"];
                };
            };
            /** @description Invalid message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Credential, renewal token, or pairing code invalid/expired/revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Station scope or authorization rejected. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session, revision, sequence, or idempotency conflict; reconcile before a new action. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Expired authorization, attempt, or command. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Back off using Retry-After. */
            429: {
                headers: {
                    /** @description Seconds before retry. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Transient failure; retry with stable identifiers and backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getConfiguration: {
        parameters: {
            query?: never;
            header: {
                /** @description Correlation UUID for reads. Responses echo this value. */
                "X-Request-ID": string;
            };
            path: {
                /** @description Must equal the authenticated station ID and any station ID in the body. */
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted response. A launch permit is not proof that a game is running or billing has started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Invalid message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Credential, renewal token, or pairing code invalid/expired/revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Station scope or authorization rejected. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session, revision, sequence, or idempotency conflict; reconcile before a new action. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Expired authorization, attempt, or command. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Back off using Retry-After. */
            429: {
                headers: {
                    /** @description Seconds before retry. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Transient failure; retry with stable identifiers and backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getStationSnapshot: {
        parameters: {
            query?: never;
            header: {
                /** @description Correlation UUID for reads. Responses echo this value. */
                "X-Request-ID": string;
            };
            path: {
                /** @description Must equal the authenticated station ID and any station ID in the body. */
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted response. A launch permit is not proof that a game is running or billing has started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Invalid message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Credential, renewal token, or pairing code invalid/expired/revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Station scope or authorization rejected. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session, revision, sequence, or idempotency conflict; reconcile before a new action. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Expired authorization, attempt, or command. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Back off using Retry-After. */
            429: {
                headers: {
                    /** @description Seconds before retry. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Transient failure; retry with stable identifiers and backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSessionSnapshot: {
        parameters: {
            query?: never;
            header: {
                /** @description Correlation UUID for reads. Responses echo this value. */
                "X-Request-ID": string;
            };
            path: {
                /** @description Must equal the authenticated station ID and any station ID in the body. */
                station_id: string;
                /** @description Must belong to the authenticated station; never grants cross-station reads. */
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted response. A launch permit is not proof that a game is running or billing has started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Invalid message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Credential, renewal token, or pairing code invalid/expired/revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Station scope or authorization rejected. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session, revision, sequence, or idempotency conflict; reconcile before a new action. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Expired authorization, attempt, or command. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Back off using Retry-After. */
            429: {
                headers: {
                    /** @description Seconds before retry. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Transient failure; retry with stable identifiers and backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    sendHeartbeat: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable UUID for one logical mutation; same key + different canonical payload returns 409. Reuse identical body on retry. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Must equal the authenticated station ID and any station ID in the body. */
                station_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description Accepted response. A launch permit is not proof that a game is running or billing has started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Invalid message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Credential, renewal token, or pairing code invalid/expired/revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Station scope or authorization rejected. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session, revision, sequence, or idempotency conflict; reconcile before a new action. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Expired authorization, attempt, or command. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Back off using Retry-After. */
            429: {
                headers: {
                    /** @description Seconds before retry. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Transient failure; retry with stable identifiers and backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    requestLaunch: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable UUID for one logical mutation; same key + different canonical payload returns 409. Reuse identical body on retry. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Must equal the authenticated station ID and any station ID in the body. */
                station_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaunchRequest"];
            };
        };
        responses: {
            /** @description Accepted response. A launch permit is not proof that a game is running or billing has started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaunchResponse"];
                };
            };
            /** @description Invalid message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Credential, renewal token, or pairing code invalid/expired/revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Station scope or authorization rejected. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session, revision, sequence, or idempotency conflict; reconcile before a new action. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Expired authorization, attempt, or command. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Back off using Retry-After. */
            429: {
                headers: {
                    /** @description Seconds before retry. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Transient failure; retry with stable identifiers and backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelLaunchAttempt: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable UUID for one logical mutation; same key + different canonical payload returns 409. Reuse identical body on retry. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Must equal the authenticated station ID and any station ID in the body. */
                station_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelLaunchRequest"];
            };
        };
        responses: {
            /** @description Accepted response. A launch permit is not proof that a game is running or billing has started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Invalid message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Credential, renewal token, or pairing code invalid/expired/revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Station scope or authorization rejected. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session, revision, sequence, or idempotency conflict; reconcile before a new action. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Expired authorization, attempt, or command. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Back off using Retry-After. */
            429: {
                headers: {
                    /** @description Seconds before retry. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Transient failure; retry with stable identifiers and backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    submitEvents: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable UUID for one logical mutation; same key + different canonical payload returns 409. Reuse identical body on retry. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Must equal the authenticated station ID and any station ID in the body. */
                station_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventsRequest"];
            };
        };
        responses: {
            /** @description Accepted response. A launch permit is not proof that a game is running or billing has started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            /** @description Invalid message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Credential, renewal token, or pairing code invalid/expired/revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Station scope or authorization rejected. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session, revision, sequence, or idempotency conflict; reconcile before a new action. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Expired authorization, attempt, or command. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Back off using Retry-After. */
            429: {
                headers: {
                    /** @description Seconds before retry. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Transient failure; retry with stable identifiers and backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    pollCommands: {
        parameters: {
            query?: {
                /** @description Opaque previous cursor; commands remain eligible until terminal acknowledgement or expiry. */
                cursor?: string;
            };
            header: {
                /** @description Correlation UUID for reads. Responses echo this value. */
                "X-Request-ID": string;
            };
            path: {
                /** @description Must equal the authenticated station ID and any station ID in the body. */
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted response. A launch permit is not proof that a game is running or billing has started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandsResponse"];
                };
            };
            /** @description Invalid message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Credential, renewal token, or pairing code invalid/expired/revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Station scope or authorization rejected. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session, revision, sequence, or idempotency conflict; reconcile before a new action. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Expired authorization, attempt, or command. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Back off using Retry-After. */
            429: {
                headers: {
                    /** @description Seconds before retry. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Transient failure; retry with stable identifiers and backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    acknowledgeCommand: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable UUID for one logical mutation; same key + different canonical payload returns 409. Reuse identical body on retry. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Must equal the authenticated station ID and any station ID in the body. */
                station_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandResultRequest"];
            };
        };
        responses: {
            /** @description Accepted response. A launch permit is not proof that a game is running or billing has started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResultResponse"];
                };
            };
            /** @description Invalid message. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Credential, renewal token, or pairing code invalid/expired/revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Station scope or authorization rejected. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session, revision, sequence, or idempotency conflict; reconcile before a new action. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Expired authorization, attempt, or command. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Back off using Retry-After. */
            429: {
                headers: {
                    /** @description Seconds before retry. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Transient failure; retry with stable identifiers and backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
